import type { MenuItem } from "./types";

const MOCK_DATE = "2026-05-19T00:00:00.000Z";

export const STATIC_FEATURED_ITEMS: MenuItem[] = [
  {
    id: "1",
    name: "Terra Signature Espresso",
    slug: "terra-signature-espresso",
    price: 45000,
    finalPrice: 45000,
    description:
      "Our house blend, featuring notes of dark cocoa, toasted hazelnut, and a hint of wild berry.",
    imageUrl: "/images/menu/terra-signature-espresso.png",
    category: {
      id: "cat-espresso",
      name: "Espresso",
      slug: "espresso",
    },
    calories: 5,
    tags: ["Signature", "House Blend"],
    isAvailable: true,
    isFeatured: true,
    discount: {
      active: false,
      type: null,
      value: null,
      label: null,
      endsAt: null,
    },
    sortOrder: 1,
    createdAt: MOCK_DATE,
    updatedAt: MOCK_DATE,
  },
  {
    id: "2",
    name: "Brown Sugar Oat Latte",
    slug: "brown-sugar-oat-latte",
    price: 60000,
    finalPrice: 60000,
    description:
      "Creamy oat milk perfectly balanced with house-made caramelized brown sugar syrup.",
    imageUrl: "/images/menu/brown-sugar-oat-latte.png",
    category: {
      id: "cat-latte",
      name: "Latte",
      slug: "latte",
    },
    calories: 190,
    tags: ["Latte", "Oat Milk"],
    isAvailable: true,
    isFeatured: true,
    discount: {
      active: false,
      type: null,
      value: null,
      label: null,
      endsAt: null,
    },
    sortOrder: 2,
    createdAt: MOCK_DATE,
    updatedAt: MOCK_DATE,
  },
  {
    id: "3",
    name: "Cold Brew Reserve",
    slug: "cold-brew-reserve",
    price: 55000,
    finalPrice: 55000,
    description:
      "Steeped for 24 hours, delivering a remarkably smooth, low-acidity profile with chocolate undertones.",
    imageUrl: "/images/menu/cold-brew-reserve.png",
    category: {
      id: "cat-coldbrew",
      name: "Cold Brew",
      slug: "cold-brew",
    },
    calories: 15,
    tags: ["Cold Brew", "Reserve"],
    isAvailable: true,
    isFeatured: true,
    discount: {
      active: false,
      type: null,
      value: null,
      label: null,
      endsAt: null,
    },
    sortOrder: 3,
    createdAt: MOCK_DATE,
    updatedAt: MOCK_DATE,
  },
  {
    id: "4",
    name: "Matcha Mist Latte",
    slug: "matcha-mist-latte",
    price: 65000,
    finalPrice: 65000,
    description:
      "Ceremonial grade matcha whisked to perfection, served with lightly sweetened steamed milk.",
    imageUrl: "/images/menu/matcha-mist-latte.png",
    category: {
      id: "cat-matcha",
      name: "Matcha",
      slug: "matcha",
    },
    calories: 160,
    tags: ["Matcha", "Latte"],
    isAvailable: true,
    isFeatured: true,
    discount: {
      active: false,
      type: null,
      value: null,
      label: null,
      endsAt: null,
    },
    sortOrder: 4,
    createdAt: MOCK_DATE,
    updatedAt: MOCK_DATE,
  },
  {
    id: "5",
    name: "Honey Cortado",
    slug: "honey-cortado",
    price: 50000,
    finalPrice: 50000,
    description:
      "Equal parts espresso and steamed milk, kissed with a touch of local wildflower honey.",
    imageUrl: "/images/menu/honey-cortado.png",
    category: {
      id: "cat-cortado",
      name: "Cortado",
      slug: "cortado",
    },
    calories: 80,
    tags: ["Cortado", "Honey"],
    isAvailable: true,
    isFeatured: true,
    discount: {
      active: false,
      type: null,
      value: null,
      label: null,
      endsAt: null,
    },
    sortOrder: 5,
    createdAt: MOCK_DATE,
    updatedAt: MOCK_DATE,
  },
  {
    id: "6",
    name: "Seasonal Pourover",
    slug: "seasonal-pourover",
    price: 70000,
    finalPrice: 70000,
    description:
      "A rotating selection of single-origin beans, meticulously brewed to highlight distinct regional flavors.",
    imageUrl: "/images/menu/seasonal-pourover.png",
    category: {
      id: "cat-pourover",
      name: "Pourover",
      slug: "pourover",
    },
    calories: 10,
    tags: ["Pourover", "Seasonal"],
    isAvailable: true,
    isFeatured: true,
    discount: {
      active: false,
      type: null,
      value: null,
      label: null,
      endsAt: null,
    },
    sortOrder: 6,
    createdAt: MOCK_DATE,
    updatedAt: MOCK_DATE,
  },
];
